Demos.SalesTracker/Models/Project.cs
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Demos.SalesTracker.Models
{
    public class Project :IRecordInfo
    {
        public int Id { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjectTechnology { get; set; }
        public string ProjectStatus { get; set; }
        [ForeignKey("Region")]
        public int RegionId { get; set; }
        [ForeignKey("SubRegion")]
        public int SubRegionId { get; set; }
        public string ClientName { get; set; }
        public string ClientIndustry { get; set; }
        public virtual Region Region { get; set; }
        public virtual SubRegion SubRegion { get; set; }
        public string Createdby { get; set; }
        public string Modifiedby { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
    }
}

Demos.SalesTracker/Models/ProjectDocument.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Demos.SalesTracker.Models
{
    public class ProjectDocument : IRecordInfo
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string FileName { get; set; }
        public string Createdby { get; set; }
        public string Modifiedby { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
    }
}

Demos.SalesTracker/Models/ProjectViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Demos.SalesTracker.Models
{
    public class ProjectViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Region { get; set; }
        public string SubRegion { get; set; }
        public string ClientName { get; set; }
        public string CleintIndustry { get; set; }
        public string ProjectStatus { get; set; }
        public string ProjectTechnology { get; set; }
        public string Createdby { get; set; }
        public string Modifiedby { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
    }
}

Demos.SalesTracker/Controllers/ProjectController.cs
using Demos.SalesTracker.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Demos.SalesTracker.Controllers
{
    public class ProjectController : Controller
    {
        ApplicationDbContext _dbContext = new ApplicationDbContext();
        DbContextHelper _dbContextHelper = new DbContextHelper();
        // GET: Project
        public ActionResult Index()
        {
            return View();
        }

        // GET: Project/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Project_Read()
        {
            var dt = _dbContext.Project.ToList();

            //   List<string>  ProjectDocuments = _dbContext.ProjectFile.Where(x=>x.ProjectId== )
            IQueryable<ProjectViewModel> pvm = _dbContext.Project.Include("Region").Include("SubRegion").Select(vm => new ProjectViewModel()
            {
                Id = vm.Id,
                Title = vm.ProjectTitle,
                ClientName = vm.ClientName,
                Created = vm.Created,
                Createdby = vm.Createdby,
                CleintIndustry = vm.ClientIndustry,
                Modified = vm.Modified,
                Modifiedby = vm.Modifiedby,
                ProjectStatus = vm.ProjectStatus,
                Region = vm.Region.Title,
                SubRegion = vm.SubRegion.Title
            });

            return Json(pvm, JsonRequestBehavior.AllowGet);
        }

        // GET: Project/Create
        public ActionResult Create()
        {
            IntializeViewdata();
            return View("ngCreate");
        }

        // POST: Project/Create
        [HttpPost]
        public ActionResult Create(Project Project, int[] projectFile, int[] supportingFile)
        {
            try
            {
                try
                {
                    // TODO: Add update logic here
                    Project.Created = DateTime.Now;
                    Project.Createdby = AppSession.UserId;
                    Project.Modified = DateTime.Now;
                    Project.Modifiedby = AppSession.UserId;
                    Project.RegionId = Convert.ToInt32(Project.Region.Id);
                    Project.SubRegionId = Convert.ToInt32(Project.SubRegion.Id);
                    _dbContextHelper.AttachToContext(Project);

                    foreach (int fle in projectFile)
                    {
                        ProjectDocumentInfo pfle = new ProjectDocumentInfo();
                        pfle.ProjectId = Project.Id;
                        pfle.ProjectDocumentId = fle;
                        _dbContextHelper.AttachToContext(pfle);
                    }

                    foreach (int sfle in supportingFile)
                    {
                        SupportingDocumentInfo spfle = new SupportingDocumentInfo();
                        spfle.ProjectId = Project.Id;
                        spfle.SupportingDocumentId = sfle;
                        _dbContextHelper.AttachToContext(spfle);
                    }
                }
                catch (Exception ex)
                {
                    return View();
                }
                IntializeViewdata();
                return View("ngCreate");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult UpdateProject(int Id)
        {
            return View("UpdateProject");
        }

        public ActionResult ngCreate()
        {
            return View();
        }
        Project result;
        // GET: Project/Edit/5
        public JsonResult Edit(int id)
        {
            if (ModelState.IsValid)
            {
                result = _dbContext.Project.Where(x => x.Id == id).FirstOrDefault();
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetRegions()
        {
            var result = _dbContext.Region.ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetSubRegions()
        {
            var result = _dbContext.SubRegion.ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetSupportingDocument()
        {
            var result = _dbContext.SuportingDocument.ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetProjectDocument()
        {
            var result = _dbContext.ProjectDocument.ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetUserInfo()
        {
            var result = _dbContext.Users.ToList();

            UserViewModel usvw = _dbContext.Users.Where(usr => usr.Id == AppSession.UserId).Select(uvm => new UserViewModel()
            {
                Id = uvm.Id,
                UserName = uvm.UserName,
                EmailId = uvm.Email,
                Designation = uvm.Designation,
                Department = uvm.Department,
                ReportingManager = _dbContext.Users.Where(usr => usr.ReportingManger.Id == uvm.Id).FirstOrDefault().UserName
            }).FirstOrDefault();
            return Json(usvw, JsonRequestBehavior.AllowGet);

        }

        // POST: Project/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Project Project)
        {
            try
            {
                // TODO: Add update logic here
                var result = _dbContext.Project.Where(x => x.Id == id).FirstOrDefault();
                Project.Created = result.Created;
                Project.Createdby = result.Createdby;
                _dbContextHelper.AttachToContext(Project);
                return Json(Project, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: Project/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Project/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public PartialViewResult UserInfoView()
        {
            var result = _dbContext.Users.ToList();

            UserViewModel usvw = _dbContext.Users.Where(usr => usr.Id == AppSession.UserId).Select(uvm => new UserViewModel()
            {
                Id = uvm.Id,
                UserName = uvm.UserName,
                EmailId = uvm.Email,
                Designation = uvm.Designation,
                Department = uvm.Department,
                ReportingManager = _dbContext.Users.Where(usr => usr.ReportingManger.Id == uvm.Id).FirstOrDefault().UserName
            }).FirstOrDefault();
            return PartialView("UserInfo", usvw);
        }

        public PartialViewResult ProjectDocumentsView()
        {
            IntializeViewdata();
            return PartialView("ProjectDocuments");
        }

        ProjectDocument pd; SupportingDocument spd;
        [HttpPost]
        public ActionResult SaveProjectDoc()
        {
            List<int> lstpd = new List<int>();

            string path = Server.MapPath("~/Attachments/");

            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            foreach (string key in Request.Files)
            {
                HttpPostedFileBase postedFile = Request.Files[key];
                postedFile.SaveAs(path + postedFile.FileName);
                try
                {
                    pd = new ProjectDocument();
                    pd.Title = postedFile.FileName.Split('.')[0];
                    pd.FileName = postedFile.FileName;
                    pd.Created = DateTime.Now;
                    pd.Createdby = AppSession.UserId;
                    pd.Modified = DateTime.Now;
                    pd.Modifiedby = AppSession.UserId;
                    _dbContextHelper.AttachToContext(pd);
                    ViewBag.ProjectDocId = pd.Id;
                    lstpd.Add(pd.Id);
                    ViewBag.ProjectDocId = lstpd;
                }
                catch (Exception ex)
                {

                }
            }


            // Return an empty string to signify success
            IntializeViewdata();
            return View("ngCreate");
        }

        public ActionResult SaveSupooritngDoc()
        {

            // The Name of the Upload component is "files"
            //if (SupportingDocFiles != null)
            //{
            //    foreach (var file in SupportingDocFiles)
            //    {
            //        // Some browsers send file names with full path.
            //        // We are only interested in the file name.
            //        var fileName = Path.GetFileName(file.FileName);
            //        var physicalPath = Path.Combine(Server.MapPath("~/Attachments/"), fileName);

            //        // The files are not actually saved in this demo
            //        TempData["fileName"] = fileName;
            //        file.SaveAs(physicalPath);

            //        try
            //        {
            //            pd = new ProjectDocument();
            //            pd.Title = fileName.Split('.')[0];
            //            pd.FileName = fileName;
            //            pd.Created = DateTime.Now;
            //            pd.Createdby = AppSession.UserId;
            //            pd.Modified = DateTime.Now;
            //            pd.Modifiedby = AppSession.UserId;

Demos.SalesTracker/Controllers/ProjectDocumentController.cs
using Demos.SalesTracker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Demos.SalesTracker.Controllers
{
    public class ProjectDocumentController : Controller
    {

        // GET: ProjectDocument
        public ActionResult Index()
        {
            return View();
        }

        // GET: ProjectDocument/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }


     
        // GET: ProjectDocument/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProjectDocument/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ProjectDocument/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ProjectDocument/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ProjectDocument/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProjectDocument/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Demos.SalesTracker/Views/Project/Create.cshtml
@model Demos.SalesTracker.Models.Project

@{
    ViewBag.Title = "Add Project";
}

<h2>Add Project</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


<div class="form-horizontal agcontainer">
    <h3>Employee Info</h3>
    @Html.Action("UserInfoView", "Project")
    <hr />
    <h3>Project Info</h3>
    <div id="projectinfocontainer" style="margin-left:50px">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "col-25" })
            <div>
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "col-75" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            @Html.LabelFor(model => model.Technology, htmlAttributes: new { @class = "col-25" })
            <div>
                @Html.EditorFor(model => model.Technology, new { htmlAttributes = new { @class = "col-75" } })

                @Html.ValidationMessageFor(model => model.Technology, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            @Html.LabelFor(model => model.ClientName, htmlAttributes: new { @class = "col-25" })
            <div>
                @Html.EditorFor(model => model.ClientName, new { htmlAttributes = new { @class = "col-75" } })
                @Html.ValidationMessageFor(model => model.ClientName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            @Html.LabelFor(model => model.Industry, htmlAttributes: new { @class = "col-25" })
            <div>
                @Html.EditorFor(model => model.Industry, new { htmlAttributes = new { @class = "col-75" } })
                @Html.ValidationMessageFor(model => model.Industry, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            @Html.LabelFor(model => model.Region, htmlAttributes: new { @class = "col-25" })
            <div>
                @Html.DropDownList("Region", ViewBag.Region as SelectList, new { htmlAttributes = new { @class = "col-75" } })
                @Html.ValidationMessageFor(model => model.Region, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            @Html.LabelFor(model => model.SubRegion, htmlAttributes: new { @class = "col-25" })
            <div>
                @Html.DropDownList("SubRegion", ViewBag.SubRegion as SelectList, new { htmlAttributes = new { @class = "col-75" } })
                @Html.ValidationMessageFor(model => model.SubRegion, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            @Html.LabelFor(model => model.ProjectStatus, htmlAttributes: new { @class = "col-25" })
            <div>
                @Html.EditorFor(model => model.ProjectStatus, new { htmlAttributes = new { @class = "col-75" } })
                @Html.ValidationMessageFor(model => model.ProjectStatus, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <hr />
    <h3>Project Documents</h3>
    @Html.Action("FileUpload", "Project")
    <div class="form-group">
        <div style="float:right">
            <input type="submit" value="Create" class="btn btn-default" />
            <input type="button" value="Cancel" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Demos.SalesTracker/Views/Project/Index.cshtml
@{
    ViewBag.Title = "Project";
}

<h2>Project</h2>

<script type="text/javascript">
    var salestrackerapp = angular.module('salestrackerapp', ['ui.grid', 'ui.grid.edit', 'ui.grid.resizeColumns', 'ui.grid.moveColumns']);

    salestrackerapp.controller('ProjectController', function ($scope, $http) {
        var vm = this;
        vm.gridOptions = {
            
        };
        vm.gridOptions.columnDefs = [
            { name: 'Title' },
            { name: 'Region' },
            { name: 'SubRegion', displayName: 'Sub Region' },
            { name: 'ProjectDocument.ProjectTitle', displayName: 'Project Documents', type: 'object' },
            { name: 'SuportingDocument.ProjectTitle', displayName: 'Suporting Documents', type: 'object' },
            { name: 'Edit', cellTemplate: '<div><a href="http://stackoverflow.com">Edit</a></div>', width: '5%' },
            { name: 'Delete', cellTemplate: '<div><a href="http://stackoverflow.com">Delete</a></div>', width: '5%' }
        ];

        $http.get('/Project/Project_Read').then(successCallback, errorCallback);
        function successCallback(response) {
            var data = response.data;
            vm.gridOptions.data = data
        }
        function errorCallback(error) {
            console.log(error);
        }

        vm.msg = {};

        vm.gridOptions.onRegisterApi = function (gridApi) {
            //set gridApi on scope
            vm.gridApi = gridApi;
            gridApi.edit.on.afterCellEdit($scope, function (rowEntity, colDef, newValue, oldValue) {
                //vm.msg.lastCellEdited = 'edited row id:' + rowEntity.Id + ' Column:' + colDef.name + ' newValue:' + newValue + ' oldValue:' + oldValue;

                vm.msg.lastCellEdited = "the field   " + colDef.name + ' is succesfully updated to ' + newValue;

                //$http.get('/Project/Edit').then(successCallback, errorCallback);

                $http.post('/Project/Edit', { 'Id': rowEntity.Id, 'Project': rowEntity }).then(successCallback, errorCallback);
                function successCallback(response) {
                    //  var data = response.data;
                    //vm.gridOptions.data = data
                }
                function errorCallback(error) {
                    console.log(error);
                }

                $scope.$apply();
            });
        };

    });
</script>

<div ng-app="salestrackerapp">
    <div ng-controller="ProjectController as $ctrl">
        <div ui-grid="$ctrl.gridOptions" ui-grid-edit class="myGrid" ui-grid-resize-columns ui-grid-move-columns></div>
        <strong>Last Cell Edited:</strong> {{$ctrl.msg.lastCellEdited}}
    </div>
</div>

Demos.SalesTracker/Views/Project/ProjectDocuments.cshtml
@{
    /**/

    ViewBag.Title = "ProjectDocuments";
}
@model Demos.SalesTracker.Models.ProjectDocument

<div id="ProjectDocumentsSection"  class="agcontainer">
    <div class="row">
        <div class="col-50-left">
            <label>Project Documents:</label>
        </div>
        <div class="col-50-right">
            <label>Supporting Documents:</label>
        </div>
    </div>
    <div class="row">
        <div class="col-50-left">
            <label>Choose From Existing Documents</label>   <br />
            <label>
                File Name:
            </label>     <br />
            <div class="form-group">
                <div class="col-md-10">
                    @Html.DropDownList("SubRegion", ViewBag.ProjectDocuments as SelectList, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <b>OR</b>  <br />
            <label>Upload Document</label>  <br />
            @using (Html.BeginForm("SaveProjectDoc", "Project", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <input type="file" id="postedFiles" multiple name="ProjectDocFiles" />
                <input type="submit" value="Upload" />
            }

        </div>
        <div class="col-50-right">
            <label>Choose From Existing Documents</label>   <br />
            <label>
                File Name:
            </label>     <br />
            <div class="form-group">
                <div class="col-md-10">
                    @Html.DropDownList("SubRegion", ViewBag.SupportingDocuments as SelectList, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <b>OR</b>  <br />
            <label>Upload Document</label>  <br />
            @using (Html.BeginForm("SaveSupooritngDoc", "Project", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <input type="file" multiple name="SupportingtDocFiles" />
                <input type="submit" value="Upload" />
            }
        </div>
    </div>
</div>

Demos.SalesTracker/Views/Project/UpdateProject.cshtml
@{
    ViewBag.Title = "UpdateProject";
}

<div ng-app="salestrackerapp" ng-controller="ProjectController" class="agcontainer">
    <form novalidate class="simple-form">
        <h3>Employee Info</h3>
        @*<div id="employeeinfocontainer" style="margin-left:20px">
            <div class="row">
                <div class="col-50-left">
                    <label>User Name:</label>
                    <label>{{UserInfo.UserName}}</label>
                </div>
                <div class="col-50-right">
                    <label>Email Id:</label>
                    <label>{{UserInfo.EmailId}}</label>
                </div>
            </div>
            <div class="row">
                <div class="col-50-left">
                    <label>Designation</label>
                    <label>{{UserInfo.Designation}}</label>
                </div>
                <div class="col-50-right">
                    <label>Department:</label>
                    <label>{{UserInfo.Department}}</label>
                </div>
            </div>
            <div class="row">
                <div class="col-50-left">
                    <label>Reporting Manager:</label>
                    <label>{{UserInfo.ReportingManager}}</label>
                </div>
            </div>
        </div>*@
        @Html.Action("UserInfoView", "Project")
        <hr />
        <h3> Project Info</h3>
        <div id="projectinfocontainer" style="margin-left:20px">
            <div class="row">
                <div class="col-25">
                    <label>Project Title:</label>
                </div>
                <div class="col-75">
                    <input type="text" ng-model="Project.Title" />
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label>Project Technology:</label>
                </div>
                <div class="col-75">
                    <input type="text" ng-model="Project.Technology" />
                </div>
            </div>

            <div class="row">
                <div class="col-25">
                    <label>Client Name:</label>
                </div>
                <div class="col-75">
                    <input type="text" ng-model="Project.ClientName" />
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label>Client Industry:</label>
                </div>
                <div class="col-75">
                    <input type="text" ng-model="Project.Industry" />
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label>Client Region:</label>
                </div>
                <div class="col-75">
                    <select id="region" ng-options="region.Title for region in Region" ng-model="selectedRegion"></select>
                    <br>
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label>Client Sub Region:</label>
                </div>
                <div class="col-75">
                    <select id="subregion" ng-options="subregion.Title for subregion in SubRegion" ng-model="selectedSubRegion"></select>
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label>Project Status:</label>
                </div>
                <div class="col-75">
                    <label>
                        <input name="status" type="radio" ng-model="color.name" ng-value="specialValue">
                        Open
                        <input name="status" type="radio" ng-model="color.name" ng-value="specialValue">
                        Closed
                    </label>
                </div>
            </div>
        </div>
        <hr />
        <h3>Documents Section</h3>
        <div id="ProjectDocumentsSection" style="margin-left:20px">
            <div class="row">
                <label>Project Documents:</label>
            </div>
            <div class="row">
                <div class="col-50-left">
                    <label>Choose From Existing Documents</label>   <br />
                    <label>
                        File Name:
                        <select ng-model="Project.Industry" ng-options="x.Title for x in ProjectDocument"></select>
                    </label>
                    <br />
                    <b>OR</b>  <br />
                    <label>Upload Document</label>  <br />
                    <input type="file" />
                </div>
                <div class="col-50-right">
                    <label>Supporting Documents:</label>
                    <label>Choose From Existing Documents</label>   <br />
                    <label>
                        File Name:
                        <select ng-model="Project.Industry" ng-options="x.Title for x in SupportingDocument"></select>
                    </label>
                    <br />
                    <b>OR</b>  <br />
                    <label>Upload Document</label>  <br />
                    <input type="file" multiple />
                </div>
            </div>
        </div>
        <div id="submit" style="float:right;clear:both;">
            <br />    <br /> <br />
            <div class="row">
                <input type="submit" ng-click="update(user)" value="Save" />
                <input type="button" ng-click="reset()" value="Reset" />
            </div>
        </div>
    </form>
</div>

<script type="text/javascript">
    var msg = ""; var regionId = 0; var subregionId = 0; var documentid = 0;
    var salestrackerapp = angular.module('salestrackerapp', []);

    salestrackerapp.controller('ProjectController', function ($scope, $http) {
        $http.get('/Project/Edit', { params: { 'id': 1 } }).then(successProjectitemsCallback, errorProjectitemsCallback);
        function successProjectitemsCallback(response) {
            $scope.Project = response.data;
            regionId = response.data.Region.Id;
            subregionId = response.data.SubRegion.Id;
        }
        function errorProjectitemsCallback(error) {
            console.log(error);
        }

        //$scope.Region = ["Asia", "Africa", "North America", "South America"];
        //$scope.selectedOption = $scope.Region[1];

        $http.get('/Project/GetRegions').then(successRegionCallback, errorRegionCallback);
        function successRegionCallback(response) {
            $scope.Region = response.data;
            $scope.selectedRegion = $scope.Region[regionId];
        }
        function errorRegionCallback(error) {
            console.log(error);
        }

        $http.get('/Project/GetSubRegions').then(successSubRegionCallback, errorSubRegionCallback);
        function successSubRegionCallback(response) {
            $scope.SubRegion = response.data;
            $scope.selectedSubRegion = $scope.SubRegion[subregionId];
        }
        function errorSubRegionCallback(error) {
            console.log(error);
        }

        $http.get('/Project/GetProjectDocument').then(successSubRegionCallback, errorSubRegionCallback);
        function successSubRegionCallback(response) {
            $scope.ProjectDocument = response.data;
            $scope.selectedProjectDocument = $scope.ProjectDocument[documentid];
        }
        function errorSubRegionCallback(error) {
            console.log(error);
        }

        $http.get('/Project/GetSupportingDocument').then(successSubRegionCallback, errorSubRegionCallback);
        function successSubRegionCallback(response) {
            $scope.ProjectDocument = response.data;
            $scope.selectedProjectDocument = $scope.ProjectDocument[documentid];
        }
        function errorSubRegionCallback(error) {
            console.log(error);
        }
    });
</script>